// Single source of truth for the component registry.
// Each descriptor declares the component name and its kind ('static' or
// 'interactive'). Keep this list alphabetical by name; the public exports
// `KNOWN_COMPONENTS` and `INTERACTIVE_COMPONENTS` are derived views.
const COMPONENTS = [
  { name: 'accordion',       kind: 'interactive' },
  { name: 'alert',           kind: 'static' },
  { name: 'aspect',          kind: 'static' },
  { name: 'avatar',          kind: 'static' },
  { name: 'avatar-group',    kind: 'static' },
  { name: 'badge',           kind: 'static' },
  { name: 'bar',             kind: 'static' },
  { name: 'body',            kind: 'static' },
  { name: 'btn',             kind: 'static' },
  { name: 'caption',         kind: 'static' },
  { name: 'card',            kind: 'static' },
  { name: 'carousel',        kind: 'interactive' },
  { name: 'checkbox',        kind: 'interactive' },
  { name: 'cluster',         kind: 'static' },
  { name: 'code',            kind: 'static' },
  { name: 'col',             kind: 'static' },
  { name: 'crumbs',          kind: 'static' },
  { name: 'combobox',        kind: 'interactive' },
  { name: 'container',       kind: 'static' },
  { name: 'counter',         kind: 'interactive' },
  { name: 'date',            kind: 'interactive' },
  { name: 'dialog',          kind: 'interactive' },
  { name: 'display',         kind: 'static' },
  { name: 'divider',         kind: 'static' },
  { name: 'drawer',          kind: 'interactive' },
  { name: 'dropzone',        kind: 'interactive' },
  { name: 'empty',           kind: 'static' },
  { name: 'field',           kind: 'interactive' },
  { name: 'file',            kind: 'interactive' },
  { name: 'footer',          kind: 'static' },
  { name: 'grid',            kind: 'static' },
  { name: 'h1',              kind: 'static' },
  { name: 'h2',              kind: 'static' },
  { name: 'h3',              kind: 'static' },
  { name: 'h4',              kind: 'static' },
  { name: 'h5',              kind: 'static' },
  { name: 'h6',              kind: 'static' },
  { name: 'hero',            kind: 'static' },
  { name: 'input',           kind: 'static' },
  { name: 'kbd',             kind: 'static' },
  { name: 'label',           kind: 'static' },
  { name: 'lead',            kind: 'static' },
  { name: 'link',            kind: 'static' },
  { name: 'list',            kind: 'static' },
  { name: 'menu',            kind: 'interactive' },
  { name: 'mono',            kind: 'static' },
  { name: 'multiselect',     kind: 'interactive' },
  { name: 'notice',          kind: 'static' },
  { name: 'otp',             kind: 'interactive' },
  { name: 'overline',        kind: 'static' },
  { name: 'pagination',      kind: 'interactive' },
  { name: 'password',        kind: 'interactive' },
  { name: 'popover',         kind: 'interactive' },
  { name: 'pre',             kind: 'static' },
  { name: 'progress',        kind: 'interactive' },
  { name: 'prose',           kind: 'static' },
  { name: 'quote',           kind: 'static' },
  { name: 'radio',           kind: 'interactive' },
  { name: 'range',           kind: 'static' },
  { name: 'range-dual',      kind: 'interactive' },
  { name: 'rating',          kind: 'interactive' },
  { name: 'row',             kind: 'static' },
  { name: 'rows',            kind: 'static' },
  { name: 'search',          kind: 'interactive' },
  { name: 'section',         kind: 'static' },
  { name: 'segmented',       kind: 'interactive' },
  { name: 'select',          kind: 'static' },
  { name: 'sidebar',         kind: 'interactive' },
  { name: 'skeleton',        kind: 'static' },
  { name: 'small',           kind: 'static' },
  { name: 'spinner',         kind: 'static' },
  { name: 'stack',           kind: 'static' },
  { name: 'stat',            kind: 'static' },
  { name: 'stepper',         kind: 'interactive' },
  { name: 'switch',          kind: 'interactive' },
  { name: 'table',           kind: 'interactive' },
  { name: 'tabs',            kind: 'interactive' },
  { name: 'tag',             kind: 'static' },
  { name: 'tag-input',       kind: 'interactive' },
  { name: 'textarea',        kind: 'static' },
  { name: 'theme-switcher',  kind: 'interactive' },
  { name: 'time',            kind: 'interactive' },
  { name: 'toast',           kind: 'static' },
  { name: 'toast-host',      kind: 'interactive' },
  { name: 'tooltip',         kind: 'interactive' },
  { name: 'topnav',          kind: 'interactive' },
];

export { COMPONENTS };

export const KNOWN_COMPONENTS = COMPONENTS.map((c) => c.name);

export const INTERACTIVE_COMPONENTS = COMPONENTS
  .filter((c) => c.kind === 'interactive')
  .map((c) => c.name);

export const KNOWN_THEMES = ['brutalist', 'corporate', 'minimal'];

export function defineConfig(config = {}) {
  return {
    prefix: config.prefix ?? 'brut',
    components: config.components ?? 'all',
    theme: config.theme ?? 'brutalist',
    themes: config.themes ?? [],
    tokens: {
      override: config.tokens?.override ?? {},
      extend: config.tokens?.extend ?? {},
    },
    variants: config.variants ?? {},
    output: {
      dir: config.output?.dir ?? 'dist',
      minify: config.output?.minify ?? true,
      manifest: config.output?.manifest ?? true,
    },
  };
}
