export const componentsSidebar = [
  { text: 'Overview', link: '/components/' },
  { text: "Accordion", link: '/components/accordion' },
  { text: "Alerts", link: '/components/alerts' },
  { text: "Avatars + Stats", link: '/components/avatars' },
  { text: "Badges + Tags", link: '/components/badges' },
  { text: "Breadcrumbs", link: '/components/breadcrumbs' },
  { text: "Buttons", link: '/components/buttons' },
  { text: "Cards", link: '/components/cards' },
  { text: "BRUT &mdash; carousel", link: '/components/carousel' },
  { text: "Combobox", link: '/components/combobox' },
  { text: "Date picker", link: '/components/date' },
  { text: "Dialog", link: '/components/dialog' },
  { text: "Drawer", link: '/components/drawer' },
  { text: "Dropzone", link: '/components/dropzone' },
  { text: "Empty state", link: '/components/empty' },
  { text: "File", link: '/components/file' },
  { text: "Footer", link: '/components/footer' },
  { text: "Form layouts", link: '/components/form-layouts' },
  { text: "Forms — every input", link: '/components/forms' },
  { text: "12-Column Grid", link: '/components/grid' },
  { text: "Inputs", link: '/components/inputs' },
  { text: "Layout", link: '/components/layout' },
  { text: "Menu", link: '/components/menu' },
  { text: "Modal / Dialog", link: '/components/modal' },
  { text: "Multi-select", link: '/components/multiselect' },
  { text: "OTP", link: '/components/otp' },
  { text: "Pagination", link: '/components/pagination' },
  { text: "Password", link: '/components/password' },
  { text: "Popover", link: '/components/popover' },
  { text: "Progress", link: '/components/progress' },
  { text: "Range slider — dual thumb", link: '/components/range-dual' },
  { text: "Rating", link: '/components/rating' },
  { text: "Rows", link: '/components/rows' },
  { text: "Search", link: '/components/search' },
  { text: "Sidebar nav", link: '/components/sidebar' },
  { text: "Skeleton", link: '/components/skeleton' },
  { text: "Spinner", link: '/components/spinner' },
  { text: "Stepper", link: '/components/stepper' },
  { text: "Table — Responsive", link: '/components/table-responsive' },
  { text: "Table — Sticky", link: '/components/table-sticky' },
  { text: "Table", link: '/components/table' },
  { text: "Tabs + Segments", link: '/components/tabs' },
  { text: "Tag input", link: '/components/tag-input' },
  { text: "Tags", link: '/components/tags' },
  { text: "Time picker", link: '/components/time' },
  { text: "Toast", link: '/components/toast' },
  { text: "Toggles + Checkboxes", link: '/components/toggles' },
  { text: "Tooltip", link: '/components/tooltip' },
  { text: "Topnav", link: '/components/topnav' },
]
